require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

RSpec/MultipleExpectations:
  Max: 10
RSpec/ExampleLength:
  Max: 10

## 開発途中での記述。開発が進み、モックが必要なくなれば解除する。
RSpec/AnyInstance:
  Enabled: false
AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
